### ISSUE TITLE
what should be passed to arguments

### ISSUE THREAD

**Issue by vishalezen** [ajmalmsali/Grire-example#1]
what should be the input to the project

`String action = args[0].toLowerCase();
        String imagePoolName = args[1].toLowerCase();
        String dbFolder = args[2].toLowerCase();
        String location = args[3];`

what are the 4 arguments

**Comment by ajmalmsali** [comment]
```
    String action       =args[0].toLowerCase();
    String imagePoolName=args[1].toLowerCase();
    String dbFolder     =args[2].toLowerCase();
    String location     =args[3];
```

action = create / search / merge.
imagePoolName = Image Pool Name.
DB Folder = database location

Have a look at the example in readme

Adding an imagefolder

java -jar ajmg6.jar create ImagePoolName /home/username/YourGrireDb/db /home/username/YourImageFilesFolder 1f multi

Searching for an Image

java -jar ajmg6.jar search ImagePoolName /home/username/YourGrireDb/db /home/username/YourSourceFile.jpg

**Comment by vishalezen** [comment]
HI,
Thank you so much for replying.

May be it is very easy.. But I am not getting what is ImagePool and how to create it. I have explored the code after my first comment. I am not getting  what is the 'ImagePool' thing.

Please reply.
